import { createApp } from "vue";
import { createPinia } from "pinia";
import "./style.css";
import App from "./App.vue";
import router from "./routes/index.js";
import Blockchain from "./infra/blockchain.js";
import Token from "./infra/token.js";
import Post from "./infra/post.js";
import Report from "./infra/report.js";

const blockchain = new Blockchain();
const post = new Post();
const token = new Token();
const report = new Report();
blockchain.init();
post.init();
token.init();
report.init();
const pinia = createPinia();
const app = createApp(App);
app.provide("reportClient", report);
app.provide("postClient", post);
app.provide("tokenClient", token);
app.provide("blockchainClient", blockchain);
app.use(router);
app.use(pinia);
app.mount("#app");
